config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, :scope => [:list_id]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)

    @list = List.find(params[:list_id])

    @bookmark.list = @list

    if @bookmark.save
      redirect_to @list
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to @bookmark.list
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for ([@list, @bookmark]) do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

<%= link_to 'Back', lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="navbar navbar-expand-sm navbar-secondary navbar-lewagon ">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://image.shutterstock.com/image-vector/film-strip-round-banner-design-260nw-260628887.jpg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%# <li class="nav-item active">
        <%= link_to "Home", "#", class: "nav-link" %>
      <%# </li> %>
      <li class="nav-item">
        <%= link_to 'New List', new_list_path, class: 'btn btn-xs btn-warning'%>
      </li>
    </ul>
  </div>
</div>


<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.cityofburnet.com/sites/default/files/styles/banner_home/public/imageattachments/banner/3701/movie_night.png?itok=lXhha1DH)">
  List of the Movies
</div>

<div class="row justify-content-center">
  <div class="col-md-9">

    <div class="cards mt-4">
      <% @lists.each do |list| %>

        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.osn.com/getattachment/watch/hot-topics/osn-blogs/May-2018/Laugh-out-loud-with-our-top-comedy-movies/ted.jpg.aspx)">

          <%= link_to list.name, list_path(list) %>
        </div>
      <% end %>

  </div>
</div>

app/views/lists/new.html.erb
<div class="navbar navbar-expand-sm navbar-secondary navbar-lewagon ">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://image.shutterstock.com/image-vector/film-strip-round-banner-design-260nw-260628887.jpg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Back', lists_path, class: 'btn btn-xs btn-secondary'%>
      </li>
    </ul>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
    <h1 class="justify-content-center">Add movie</h1>
      <%= simple_form_for(@list) do |f| %>
        <%= f.input :name %>
        <%= f.submit "Submit review",  class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="navbar navbar-expand-sm navbar-secondary navbar-lewagon ">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://image.shutterstock.com/image-vector/film-strip-round-banner-design-260nw-260628887.jpg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active" >
        <%= link_to 'Add a bookmark', new_list_bookmark_path(@list), class: 'btn btn-xs btn-primary mx-2 '%>
      </li>
      <li class="nav-item">
        <%= link_to 'Back', lists_path, class: 'btn btn-xs btn-secondary'%>
      </li>

    </ul>
  </div>
</div>


<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1585951237318-9ea5e175b891?ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8bW92aWV8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60)">
</div>

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-9">
      <div class="card-product">
        <% @list.bookmarks.each do |bookmark| %>
          <img src="<%=bookmark.movie.poster_url%>">
            <div class="card-product-infos">

              <h2><%= bookmark.movie.title %></h2>
              <p><%= bookmark.movie.overview %><br>
              <a href="<%= bookmark.movie.poster_url %>" alt="poster_url"></p>
              <span><%= bookmark.movie.rating %></span>
              <p><%= bookmark.comment %></p>

              <%= link_to 'Destroy',
                            bookmark,
                            method: :delete,
                            class: 'btn btn-xs btn-danger',
                            data: { confirm: 'Are you sure?' } %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>